---
- name: check targets
  hosts: dev
  user: ansible
  become: yes
  connection: ssh
  gather_facts: yes
  tasks:
    - name: remove docker container if exists
      command: docker rm -f chandu
      ignore_errors: yes
    - name: remove image
      command: docker rmi $(docker images -q)
      ignore_errors: yes
    - name: run container
      command: docker run -it -d --name chandu -p 8081:8080 kulashekaralwarn/devops
