---
- name: check targets
  hosts: dev
  user: ansible
  become: yes
  connections: ssh
  tasks:
    - name: remove docker container if exists
      command: docker rm -f chandu
    - name: remove image
      command: docker rmi $(docker images -q)
    - name: run container
      command: docker run -it -d --name chandu -p 8081:8080 kulashekaralwarn/devops
